name: Deployment (re-use)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      remote_host:
        required: true
        type: string
    secrets:
      REMOTE_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy using Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: call
          args: deploy-server --remote-host ${{ inputs.remote_host }} --remote-user env://REMOTE_USER --ssh-private-key env://SSH_PRIVATE_KEY
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
