on: [push, workflow_dispatch]

name: "Main pipeline: build, lint, test"
jobs:
  Main:
    name: Main
    runs-on: ubuntu-latest
    env:
      NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: joepmeneer
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: joepmeneer/atomic-server
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger CI (test, lint, build)
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: ci --netlify-auth-token env://NETLIFY_TOKEN
      - name: Dagger docker images (build images & publish)
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: create-docker-images --tags ${{ steps.meta.outputs.tags }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./artifact
